# Generated by Django 5.2.3 on 2025-06-24 07:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('ENGINEERING', 'Engineering'), ('QA', 'Quality Assurance'), ('DEVOPS', 'DevOps'), ('PRODUCT', 'Product Management'), ('DESIGN', 'UI/UX Design'), ('MARKETING', 'Marketing'), ('HR', 'Human Resources'), ('SALES', 'Sales')], max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('hire_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_working_days', models.IntegerField(default=0)),
                ('total_working_hours', models.FloatField(default=0.0)),
                ('days_forgot_checkout', models.IntegerField(default=0)),
                ('days_off', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timekeeping.employee')),
            ],
            options={
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('FORGOT_CHECKOUT', 'Forgot to Checkout')], default='CHECKED_OUT', max_length=20)),
                ('working_hours', models.FloatField(default=0.0)),
                ('forgot_checkout', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timekeeping.employee')),
            ],
            options={
                'ordering': ['-date', '-check_in_time'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
